title: "RobLabs.com"
description: "Map product research for Web, Print and Mobile."
url: https://roblabs.com
permalink: pretty           # https://jekyllrb.com/docs/permalinks/
lang: en-US
remote_theme: benbalter/retlab    # https://github.com/benbalter/retlab

# Open Graph
twitter:
  site: "@RobLabs"
  creator: "@RobLabs"

# https://jekyllrb.com/docs/configuration/options/#global-configuration
destination: ./tmp/_site/www
encoding: UTF-8
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "go.sh", ".DS_Store", "ssl", ".ruby-version"]
timezone: America/Los_Angeles

# https://jekyllrb.com/docs/configuration/markdown/#kramdown
# Kramdown is the default Markdown renderer for Jekyll, and often works well with no additional configuration.
# markdown: kramdown

# https://jekyllrb.com/docs/pagination/
paginate: 25
paginate_path: "/blog/page:num/"

# Pages to include in header navigation
nav_pages:
  - index.html

# Pages to include in footer navigation
footer_pages:

# https://jekyllrb.com/docs/front-matter/
# Front matter defaults
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post
      comments: true
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page
      comments: false

# https://jekyllrb.com/docs/plugins/
plugins:
  - jekyll-avatar           # https://github.com/jekyll/jekyll-avatar
  - jekyll-redirect-from    # https://github.com/jekyll/jekyll-redirect-from
  - jekyll-remote-theme     # https://github.com/benbalter/jekyll-remote-theme
  - jekyll-paginate         # https://github.com/jekyll/jekyll-paginate
  - jekyll-seo-tag          # https://github.com/jekyll/jekyll-seo-tag
  - jekyll-sitemap          # https://github.com/jekyll/jekyll-sitemap
  - jekyll-github-metadata  # https://github.com/jekyll/github-metadata
  - jekyll-feed             # https://jekyllrb.com/docs/configuration/options/#serve-command-options

# https://jekyllrb.com/docs/configuration/options/#serve-command-options
livereload: true
livereload_min_delay: 6
livereload_max_delay: 10