title: Rob | Labs
site_name: Rob Labs
email: web@Rob|Labs.com
twitter_username: e_pi_rational
github_username:  roblabs
twitter:
  site: "@RobLabs"
  creator: "@RobLabs"
github: [metadata]

# global settings
title: "RobLabs.com"
description: "Map innovations for Web, Print and Mobile."
url: https://roblabs.com
permalink: pretty
relative_permalinks: false

destination: ./tmp/_site/www
paginate: 25
paginate_path: "/blog/page:num/"

# build settings
exclude: ["script", "vendor", "bower.json", "Gemfile", "Gemfile.lock", "Rakefile", "readme.md", "package.json", "go.sh", ".DS_Store", "ssl"]

markdown: CommonMarkGhPages
# commonmark:
#   options: ["SMART", "FOOTNOTES"]
#   extensions: ["strikethrough", "autolink", "table"]  # Valid extensions: table, strikethrough, autolink, tagfilter

# markdown: kramdown
# kramdown:
#   parse_block_html: true

plugins:
  - jekyll-avatar
  - jekyll-redirect-from
  - jekyll-seo-tag
  - jekyll-coffeescript
  - jekyll-sitemap
  - jekyll-paginate
  - jekyll-github-metadata

sass:
  style: :compressed
